const express = require("express")
const { model } = require("mongoose")
const { insertDB, quizDb } = require("../controller/Dbcontoller")
const { Signup, Login, Find, setPassword, sendOtp, expiry } = require("../controller/authcontroller")
const {  quizlist, insertquiz } = require("../controller/quizcontrooler")
const { insertHMTL, HTMLlist } = require("../controller/HTMLcontroller")
const { insertCSS, CSSlist } = require("../controller/CSScontroller")
const { adddata } = require("../controller/datacontoller")
const {customadd, Customquizlist, deletequiz} = require("../controller/Customcontoller")
const {  verifyOtp } = require("../controller/verification")
const { Aiadd } = require("../controller/Aicontroller")
const { authMiddleware } = require("../middlewaer/authmiddlewear")
const { transaction } = require("../controller/transactioncontroller")
const { adminmail } = require("../service/adminmail")
const { Limitcontroller } = require("../controller/Limitcontoller")

let Router = express.Router()
let DbRouter = express.Router()
let HTMLRouter = express.Router()
let CSSRouter = express.Router()
let authrouter = express.Router()
let datarouter = express.Router()
let Custom = express.Router()
let verfiyRoute = express.Router()
let Findroute = express.Router()
let Airoute = express.Router()

Router.post("/insert",insertquiz)
Router.get("/list",quizlist)
DbRouter.post("/insert",insertDB)
DbRouter.get("/list",quizDb)
HTMLRouter.post("/insert",insertHMTL)
HTMLRouter.get("/list",HTMLlist)
CSSRouter.post("/insert",insertCSS)
CSSRouter.get("/list",CSSlist)
authrouter.post("/signup",Signup)
authrouter.post("/login",Login)
datarouter.post("/add",adddata)
Custom.post("/customadd",customadd)
Custom.get("/list",Customquizlist)
Custom.post("/Aiadd",authMiddleware,Limitcontroller,Aiadd)
Custom.post("/customdelete",deletequiz)
verfiyRoute.post('/auth/verify-otp',verifyOtp)
Findroute.post('/auth/findgmail',Find)
Findroute.post('/auth/reset-password',setPassword)
Findroute.get('/expiry',authMiddleware,expiry)
Airoute.post('/submit-transaction',authMiddleware,transaction,adminmail)

module.exports={DbRouter,Router,HTMLRouter,CSSRouter,authrouter,datarouter,Custom,verfiyRoute,Findroute,Airoute}